print("Hello GitHub")
print("I'm learning Git")
print("This message comes from feature-greeting")
print("This line comes from master")
print("This line comes from feature branch")
print("Local change before push")
print("Change made on GitHub")
